# Generated by Django 4.2.5 on 2023-09-30 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('articulo_deportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.articulodeportivo')),
            ],
        ),
        migrations.CreateModel(
            name='Univalluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipoUnivalluno', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(max_length=60)),
                ('numeroDocumento', models.CharField(max_length=10)),
                ('codigoEstudiante', models.CharField(max_length=10)),
                ('correoElectrónico', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MiModelo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='univalluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.univalluno'),
        ),
    ]
