# Generated by Django 4.2.5 on 2023-09-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_articulodeportivo_prestamo_univalluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulodeportivo',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='univalluno',
            name='correoElectrónico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='univalluno',
            name='tipoDocumento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='univalluno',
            name='tipoUnivalluno',
            field=models.CharField(max_length=100),
        ),
    ]
