# Generated by Django 4.2.5 on 2023-10-02 02:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_alter_articulodeportivo_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='articulo_deportivo',
            new_name='articuloDeportivo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_prestamo',
        ),
        migrations.AddField(
            model_name='articulodeportivo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fechaHoraPrestamo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fechaHoraVencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 20, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='articulodeportivo',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
