# Generated by Django 4.2.5 on 2023-10-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_rename_articulo_deportivo_prestamo_articulodeportivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulodeportivo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articulodeportivo',
            name='valor',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
