# Generated by Django 4.2.5 on 2023-10-02 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_multas'),
    ]

    operations = [
        migrations.AddField(
            model_name='multas',
            name='prestamo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.prestamo'),
        ),
        migrations.AddField(
            model_name='multas',
            name='univalluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.univalluno'),
        ),
        migrations.AlterField(
            model_name='multas',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
